#####################################################################################
#                                   WARNING                                         #
#####################################################################################
#                                                                                   #
# This file is synchronised across all supportpal/addon-language-* repositories.    #
# Be careful not to hardcode any paths, and only update it in the                   #
# supportpal/addon-language-english repository!                                     #
#                                                                                   #
#####################################################################################
name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2, supportpal/language-tools

      - name: PHP Syntax Check
        uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=vendor

      - name: Set environment
        run: |
          LANG_PATH=$(find Lang -mindepth 1 -maxdepth 1 -type d -print -quit)
          echo "LANG_PATH=$(echo $LANG_PATH)" >> $GITHUB_ENV
          echo "LANG_NAME=$(basename $LANG_PATH)" >> $GITHUB_ENV 

      - name: Check out English
        if: ${{ env.LANG_NAME != 'en' }}
        uses: actions/checkout@v4
        with:
          repository: supportpal/addon-language-english
          path: addon-language-english/
          ref: master

      - name: Code Quality
        if: ${{ env.LANG_NAME != 'en' }}
        run: |
          language-tools compare addon-language-english/Lang/en/ Lang/${{ env.LANG_NAME }}
